routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::domain('{store}.domain')->middleware(['web', 'dynamic.subdomain'])->name('frontend.')->group(function () {

    Auth::routes();

    Route::get('/', 'MainController@main')->name('main');

    Route::get('/home', 'HomeController@index');
    Route::resource('products', 'ProductController')->only(['index', 'show']);
    Route::resource('categories', 'CategoryController')->only(['index', 'show']);
    Route::resource('pages', 'PageController')->only(['show']);
    Route::resource('comments', 'CommentController')->only(['store']);

});


Route::domain('aleapi')->group(function () {

    Route::get('/', function () {
        return view('main');
    });

    //dashboard

    Route::middleware(['web', 'auth:manager'])->namespace('Dashboard')->prefix('dashboard')->name('dashboard.')->group(function () {
        Route::resource('stores', 'StoreController');

        //prefix->{store} in middleware->manager.stores
        Route::middleware(['manager.stores', 'dynamic.subdomain'])->prefix('{store}')->name('store.')->group(function () {
            Route::get('/main', 'MainController@index')->name('main');
            Route::resource('sliders', 'SliderController')->except(['show']);
            Route::resource('categories', 'CategoryController')->except(['show']);
            Route::resource('pages', 'PageController')->except(['show']);
            Route::resource('embed-codes', 'EmbedCodeController')->except(['show']);
            Route::resource('products', 'ProductController')->except(['show']);
            Route::get('comments/change/{comment}', 'CommentController@change')->name('comments.change');
            Route::resource('comments', 'CommentController')->only(['index', 'update', 'edit', 'destroy']);
            Route::resource('exclusive-products', 'ExclusiveProductController')->except(['show']);

            Route::get('custom-options', 'OptionController@edit')->name('custom-options.edit');
            Route::put('custom-options', 'OptionController@update')->name('custom-options.update');

            Route::resource('images', 'ImageController')->only(['destroy']);
            Route::post('partner-products', 'PartnerProductController@search')->name('partner.products.search');
//            Route::post('partner-products/{search}', 'PartnerProductController@search')->name('partner.products.search');

        });

    });

    Route::namespace('Dashboard')->name('dashboard.')->group(function () {
        Auth::routes();
    });

});

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Facades\SubDomainService;
use App\Http\Requests\Dashboard\StoreCategory;
use App\Http\Requests\Dashboard\UpdateCategory;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Validator;

class CategoryController extends Controller
{
    public function index(Category $category)
    {
        $categories = $category->all();

        $prepareTree = $category->preparationForTree($categories->toArray());

        $tree = null;
        $categoryModel = null;

        if (!empty($prepareTree)){
            $tree = $category->createTreeHyphen($prepareTree,  min(array_keys($prepareTree)));
            $categoryModel = $category;
        }

        return view('dashboard.categories.index', compact('categoryModel', 'tree'));
    }

    public function create(Category $category)
    {
        $categories = Category::all();

        $tree = null;
        $prepareTree = null;

        if(!$categories->isEmpty()){
            $prepareTree = $category->preparationForTree($categories->toArray());
            $tree = $category->createTreeHyphen($prepareTree,  min(array_keys($prepareTree)));
        }

        return view('dashboard.categories.create', compact('tree'));
    }

    public function store(StoreCategory $request, Category $category)
    {
        $category->fill($request->validated());

        $category->slug = str_slug($category->name);

        if (is_null($category->parent_id)){
            $category->parent_id = 0;
            $category->position  = 1 + ($category->max('position') ?? 0);
        }else{
            $category->position  = 1 + ($category->whereParentId($category->parent_id)->max('position') ?? 0);
        }

        $category->save();

        return redirect()->route('dashboard.store.categories.index');
    }

    public function edit(Category $category)
    {
        $categories = $category->where('id', '!=', $category->id)->where('parent_id', '!=', $category->id)->get();

        $tree = null;
        $prepareTree = null;

        if(!$categories->isEmpty()){
            $prepareTree = $category->preparationForTree($categories->toArray());
            $tree = $category->createTreeHyphen($prepareTree, min(array_keys($prepareTree)));
        }

        return view('dashboard.categories.edit', compact('category', 'tree'));
    }

    public function update(UpdateCategory $request, Category $category)
    {
        $valid = Validator::make($request->all(), [
            'parent_id'     => 'required',
        ]);

        $id = Category::where('slug', $request->segment(4))->first()->id;

        $valid->sometimes(
            ['parent_id'],
            Rule::exists('categories', 'id')->where(function ($query) use ($id) {
                return $query->where('store_id', SubDomainService::getStoreId())->where('parent_id', '!=', $id);
            }),
            function($input){
                return ($input->parent_id != 0) ? true : false;
            }
        );

        if($valid->fails()){
            return redirect()->back()
                ->withErrors($valid)
                ->withInput();
        }

        $category->fill($request->validated());
        $category->slug = str_slug($category->name);
        $category->parent_id = $request->parent_id;

        $category->save();

        return redirect()->route('dashboard.store.categories.index');
    }

    public function destroy(Category $category)
    {
        DB::transaction(function () use ($category){
            $category->where('parent_id', $category->id)->update(['parent_id' => $category->parent_id]);
            $category->delete();
        });

        return redirect()->route('dashboard.store.categories.index');
    }
}

app/Http/Controllers/Dashboard/CommentController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\UpdateComment;
use App\Models\Comment;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CommentController extends Controller
{
    public function index()
    {
        $comments = Comment::orderBy('id', 'DESC')->get();

        return view('dashboard.comments.index', compact('comments'));
    }

    public function change(Comment $comment)
    {
        $comment->is_visible = (!$comment->is_visible);
        $comment->save();

        return response()->json($comment->only('is_visible'));
    }

    public function edit(Comment $comment)
    {
        return view('dashboard.comments.edit', compact('comment'));
    }

    public function update(UpdateComment $request, Comment $comment)
    {
        $comment->fill($request->validated());
        $comment->save();
        return redirect()->route('dashboard.store.comments.index');
    }

    public function destroy(Comment $comment)
    {
        $comment->delete();
        return redirect()->route('dashboard.store.comments.index');
    }


}

app/Http/Controllers/Dashboard/EmbedCodeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\StoreEmbedCode;
use App\Http\Requests\Dashboard\UpdateEmbedCode;
use App\Models\EmbedCode;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class EmbedCodeController extends Controller
{
    public function index()
    {
        $embedCode = EmbedCode::all();
        return view('dashboard.embed_code.index', compact('embedCode'));
    }

    public function create()
    {
        return view('dashboard.embed_code.create');
    }

    public function store(StoreEmbedCode $request, EmbedCode $embedCode)
    {
        $embedCode->fill($request->validated());

        $embedCode->save();

        return redirect()->route('dashboard.store.embed-codes.index');

    }

    public function show($id)
    {
        //
    }

    public function edit(EmbedCode $embedCode)
    {
        return view('dashboard.embed_code.edit', compact('embedCode'));
    }

    public function update(UpdateEmbedCode $request, EmbedCode $embedCode)
    {
        $embedCode->fill($request->validated());
        $embedCode->save();

        return redirect()->route('dashboard.store.embed-codes.index');
    }

    public function destroy(EmbedCode $embedCode)
    {
        $embedCode->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/ExclusiveProductController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\StoreExclusiveProduct;
use App\Http\Requests\Dashboard\UpdateExclusiveProduct;
use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\ExclusiveProduct as Exclusive;

class ExclusiveProductController extends Controller
{
    public function index()
    {
        $exclusives = Exclusive::with('product')->get();
        return view('dashboard.exclusive-products.index', compact('exclusives'));
    }

    public function create()
    {
        $products = Product::All();
        return view('dashboard.exclusive-products.create', compact('products'));
    }

    public function store(StoreExclusiveProduct $request, Exclusive $exclusive)
    {
        $exclusive->fill($request->validated());

        if(!empty($request->validated()['main'])){
            $exclusive->main = Exclusive::MAIN_PRODUCT;
            Exclusive::where('main', Exclusive::MAIN_PRODUCT)->update(['main' => Exclusive::SUB_PRODUCT]);
        }

        $exclusive->save();

        return redirect()->route('dashboard.store.exclusive-products.index');
    }

    public function edit(Exclusive $exclusiveProduct)
    {
        $products = Product::all();
        return view('dashboard.exclusive-products.edit', compact('products', 'exclusiveProduct'));
    }

    public function update(UpdateExclusiveProduct $request, Exclusive $exclusiveProduct)
    {
        $exclusiveProduct->fill($request->validated());

        if(isset($request->validated()['main'])){
            Exclusive::where('main', Exclusive::MAIN_PRODUCT)->where('id', '!=', $exclusiveProduct->id)->update(['main' => Exclusive::SUB_PRODUCT]);
            $exclusiveProduct->main = Exclusive::MAIN_PRODUCT;
        }else{
            $exclusiveProduct->main = Exclusive::SUB_PRODUCT;
        }

        $exclusiveProduct->save();

        return redirect()->route('dashboard.store.exclusive-products.index');
    }

    public function destroy(Exclusive $exclusiveProduct)
    {
        $exclusiveProduct->delete();
        return redirect()->back();
    }
}

app/Http/Controllers/Dashboard/ImageController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Image;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ImageController extends Controller
{
    public function destroy (Image $image)
    {
        $image->delete();
        return response()->json($image, 200);
    }
}

app/Http/Controllers/Dashboard/MainController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class MainController extends Controller
{
    public function index()
    {
//        $this->_epnApiAccess->AddRequestGetTopMonthly('top_sales_1', 'ru', 'RUR', 'sales');
//        $this->_epnApiAccess->RunRequests();
//
//        $offers = $this->_epnApiAccess->GetRequestResult('top_sales_1')['offers'];
//
//        $this->_epnApiAccess->AddRequestGetOfferInfo('one', $offers[0]['id']);
//        $this->_epnApiAccess->AddRequestGetOfferInfo('two', $offers[1]['id']);
//        $this->_epnApiAccess->AddRequestGetOfferInfo('three', $offers[2]['id']);
//        $this->_epnApiAccess->AddRequestGetOfferInfo('four', $offers[3]['id']);
//        $this->_epnApiAccess->AddRequestGetOfferInfo('five', $offers[4]['id']);
//
//        $this->_epnApiAccess->RunRequests();
//
//        dump($this->_epnApiAccess->GetRequestResult('one'));
//        dump($this->_epnApiAccess->GetRequestResult('two'));
//        dump($this->_epnApiAccess->GetRequestResult('three'));
//        dump($this->_epnApiAccess->GetRequestResult('four'));
//        dump($this->_epnApiAccess->GetRequestResult('five'));

//        dump(Auth::user()->email);

        return view('dashboard.main');
    }
}

app/Http/Controllers/Dashboard/OptionController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Facades\OptionsService;
use App\Http\Requests\Dashboard\UpdateOption;
use App\Models\Option;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class OptionController extends Controller
{
    public function edit()
    {
        $options = OptionsService::getSortedOptions();
        return view('dashboard.options.edit', compact('options'));
    }

    public function update(UpdateOption $request, Option $option)
    {
        $code = 200;

        foreach ($request->validated() as $key => $item) {
            $option->whereName($key)->update(['value' => $item]) || $code = 400;
        }

        return response()->json($request, $code);
    }
}

app/Http/Controllers/Dashboard/PageController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Requests\Dashboard\StorePage;
use App\Http\Requests\Dashboard\UpdatePage;
use App\Models\Page;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PageController extends Controller
{
    public function index()
    {
        $pages = Page::all();
        return view('dashboard.pages.index', compact('pages'));
    }

    public function create()
    {
        return view('dashboard.pages.create');
    }

    public function store(StorePage $request, Page $page)
    {
        $image = $request->file('image');

        $page->fill($request->validated());
        $page->image = $page->saveImage($image);

        $page->save();
        return redirect()->route('dashboard.store.pages.index');
    }

    public function show($id)
    {
        //
    }

    public function edit(Page $page)
    {
        return view('dashboard.pages.edit', compact('page'));
    }

    public function update(UpdatePage $request, Page $page)
    {
        $page->fill($request->validated());

        if(!is_null($request->image)){
            $page->image = $page->saveImage($request->file('image'));
        }

        $page->save();

        return redirect()->route('dashboard.store.pages.index');
    }

    public function destroy(Page $page)
    {
        $page->delete();
        return redirect()->route('dashboard.store.pages.index');
    }
}

app/Http/Controllers/Dashboard/PartnerProductController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Facades\SubDomainService;
use App\Models\Partners\Factory;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PartnerProductController extends Controller
{

    protected $partner = null;

    public function __construct(Factory $factory)
    {
        $this->partner = $factory->create(SubDomainService::getProgram(), SubDomainService::getUserApiKey(), SubDomainService::getUserPrivateKey(), SubDomainService::getUserHash());
    }

    public function search(Request $request)
    {
        $params = [
            'limit' => $request->api_limit,
            'lang' => $request->api_lang,
            'orderby' => $request->api_orderby ?? '',
            'offset' => 0,
            'category' => $asd = implode(",", $request->api_categoriesList),
            'currency' => $request->api_currency,
        ];

        return response()->json($this->partner->search($request->search, $params), 200);
    }

}

resources/views/dashboard/pages/create.blade.php
@extends('dashboard.layouts.dashboard-store')

@section('content')
    <div id="content" class="content">

        <h1 class="page-header">Страницы</h1>
        <div class="panel panel-inverse" data-sortable-id="ui-widget-1">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                </div>
                <h4 class="panel-title">Страницы</h4>
            </div>
            <div class="panel-body">
                <div class="sw-container" >
                    <div class="step-content">
                        <div class="row">
                            <div class="col-md-10 offset-md-1">
                                <legend class="f-w-700 p-b-0 m-t-0 m-b-20 f-s-16 text-inverse"></legend>

                                <form action="{{route('dashboard.store.pages.store')}}" method="POST" enctype="multipart/form-data">
                                    @csrf

                                    <div class="form-group row m-b-12">
                                        <div class="col-md-12">
                                            <textarea name="text" id="editor">{{ old('text') }}</textarea>
                                            @if ($errors->has('text'))
                                                <ul class="parsley-errors-list filled">
                                                    <li class="parsley-pattern">{{ $errors->first('text') }}</li>
                                                </ul>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row m-b-10">
                                        <label class="col-md-3 text-md-right col-form-label">Slug</label>
                                        <div class="col-md-6">
                                            <input type="text" name="slug" placeholder="Slug" class="form-control {{ $errors->has('slug') ? ' parsley-error' : '' }}" value="{{ old('slug') }}">
                                            @if ($errors->has('slug'))
                                                <ul class="parsley-errors-list filled">
                                                    <li class="parsley-pattern">{{ $errors->first('slug') }}</li>
                                                </ul>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row m-b-10">
                                        <label class="col-md-3 text-md-right col-form-label">Заголовок</label>
                                        <div class="col-md-6">
                                            <input type="text" name="title" placeholder="Заголовок" class="form-control {{ $errors->has('email') ? ' parsley-error' : '' }}" value="{{ old('title') }}">
                                            @if ($errors->has('title'))
                                                <ul class="parsley-errors-list filled">
                                                    <li class="parsley-pattern">{{ $errors->first('title') }}</li>
                                                </ul>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row m-b-10">
                                        <label class="col-md-3 text-md-right col-form-label">Описание</label>
                                        <div class="col-md-6">
                                            <input type="text" name="description" placeholder="Описание" class="form-control {{ $errors->has('description') ? ' parsley-error' : '' }}" value="{{ old('description') }}">

                                            @if ($errors->has('description'))
                                                <ul class="parsley-errors-list filled">
                                                    <li class="parsley-pattern">{{ $errors->first('description') }}</li>
                                                </ul>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group row m-b-10">
                                        <label class="col-md-3 text-md-right col-form-label">Keywords</label>
                                        <div class="col-md-6">
                                            <input type="text" name="keywords" placeholder="Keywords" class="form-control {{ $errors->has('keywords') ? ' parsley-error' : '' }}" value="{{ old('keywords') }}">

                                            @if ($errors->has('keywords'))
                                                <ul class="parsley-errors-list filled">
                                                    <li class="parsley-pattern">{{ $errors->first('keywords') }}</li>
                                                </ul>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row m-b-10">
                                        <label class="col-md-3 text-md-right col-form-label">Картинка</label>
                                        <div class="col-lg-6">
                                            <input type="file" class="p-t-5" name="image">

                                            @if ($errors->has('image'))
                                                <ul class="parsley-errors-list filled">
                                                    <li class="parsley-pattern">{{ $errors->first('image') }}</li>
                                                </ul>
                                            @endif
                                        </div>
                                    </div>
                                    <div class="form-group row m-b-10">
                                        <label class="col-md-3 text-md-right col-form-label">Показать</label>
                                        <div class="col-md-6">
                                            <select class="form-control" name="is_visible">
                                                <option value="1" selected="selected">Да</option>
                                                <option value="0">Нет</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="text-center">
                                        <button type="submit" class="btn btn-success">Создать</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('end-body-scripts')

    <script src="{{ asset('assets/plugins/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/plugins/ckeditor/samples/js/sample.js') }}"></script>

    <script>
        var editor = CKEDITOR.replace( 'editor',{
            filebrowserBrowseUrl : '/elfinder/ckeditor',
        });
    </script>
@endpush

resources/views/dashboard/pages/index.blade.php
@extends('dashboard.layouts.dashboard-store')

@section('content')
    <div id="content" class="content">
        <ol class="breadcrumb pull-right">
            <li class="breadcrumb-item"><a href="{{route('dashboard.store.pages.create')}}" id="add-regular" class="btn btn-sm btn-inverse">Создать страницу</a></li>
        </ol>
        <h1 class="page-header">Страницы</h1>
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <h4 class="panel-title">Страницы</h4>
            </div>
            <div class="panel-body">
                @if(!is_null($pages))
                    <table id="data-table-default" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th width="1%">Поз.</th>
                                <th width="1%" data-orderable="false">Картинка</th>
                                <th class="text-nowrap">slug</th>
                                <th class="text-nowrap">Заголовок</th>
                                <th class="text-nowrap">Описание</th>
                                <th class="text-nowrap">Keywords</th>
                                <th class="text-nowrap">Показывать</th>
                                <th class="text-nowrap">Действия</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($pages as $key => $page)
                            <tr class="@if ($key % 2) odd @else even @endif gradeX">
                                <td width="1%" class="f-s-600 text-inverse">{{$page->id}}</td>
                                <td width="4%" class="with-img"><img src="{{asset($page->image)}}" class="img-rounded height-150" /></td>
                                <td>{{$page->slug}}</td>
                                <td>{{$page->title}}</td>
                                <td>{{$page->description}}</td>
                                <td>{{$page->keywords}}</td>
                                <td>{{$page->is_visible ? 'Да' : 'Нет'}}</td>
                                <td>
                                    <a href="{{route('dashboard.store.pages.edit', $page->slug)}}"  class="btn btn-outline-primary btn-sm">Edit</a>
                                    <form method="post" action="{{route('dashboard.store.pages.destroy', $page->slug)}}" class="btn p-0">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif
            </div>
        </div>
    </div>
@endsection