routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::domain('{store}.domain')->middleware(['web', 'dynamic.subdomain'])->name('frontend.')->group(function () {

    Auth::routes();

    Route::get('/', 'MainController@main')->name('main');

    Route::get('/home', 'HomeController@index');
    Route::resource('products', 'ProductController')->only(['index', 'show']);
    Route::resource('categories', 'CategoryController')->only(['index', 'show']);
    Route::resource('pages', 'PageController')->only(['show']);
    Route::resource('comments', 'CommentController')->only(['store']);

});


Route::domain('aleapi')->group(function () {

    Route::get('/', function () {
        return view('main');
    });

    //dashboard

    Route::middleware(['web', 'auth:manager'])->namespace('Dashboard')->prefix('dashboard')->name('dashboard.')->group(function () {
        Route::resource('stores', 'StoreController');

        //prefix->{store} in middleware->manager.stores
        Route::middleware(['manager.stores', 'dynamic.subdomain'])->prefix('{store}')->name('store.')->group(function () {
            Route::get('/main', 'MainController@index')->name('main');
            Route::resource('sliders', 'SliderController')->except(['show']);
            Route::resource('categories', 'CategoryController')->except(['show']);
            Route::resource('pages', 'PageController')->except(['show']);
            Route::resource('embed-codes', 'EmbedCodeController')->except(['show']);
            Route::resource('products', 'ProductController')->except(['show']);
            Route::get('comments/change/{comment}', 'CommentController@change')->name('comments.change');
            Route::resource('comments', 'CommentController')->only(['index', 'update', 'edit', 'destroy']);
            Route::resource('exclusive-products', 'ExclusiveProductController')->except(['show']);

            Route::get('custom-options', 'OptionController@edit')->name('custom-options.edit');
            Route::put('custom-options', 'OptionController@update')->name('custom-options.update');

            Route::resource('images', 'ImageController')->only(['destroy']);
            Route::post('partner-products', 'PartnerProductController@search')->name('partner.products.search');
//            Route::post('partner-products/{search}', 'PartnerProductController@search')->name('partner.products.search');

        });

    });

    Route::namespace('Dashboard')->name('dashboard.')->group(function () {
        Auth::routes();
    });

});

app/Models/Category.php
<?php

namespace App\Models;

class Category extends BaseModel
{
    CONST PARENT_CATEGORY = 0;

    protected $fillable = [
        'slug', 'parent_id', 'name', 'description', 'keywords', 'position', 'is_visible'
    ];

    public function products()
    {
        return $this->belongsToMany(Product::class);
    }

    public function productsCount()
    {
        return $this->hasOne(CategoryProduct::class)
            ->selectRaw('category_id, count(*) as count')
            ->groupBy('category_id');
    }


    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function preparationForTree($date)
    {

        $tree = [];

        foreach ($date as $item) {
            $tree[$item['parent_id']][] = $item;
        }

        return $tree;
    }

    public function createTreeHyphen($date, $parent_id = 0, $hyphen = '', &$res = [], &$level = 1)
    {

        if(empty($date[$parent_id])){
            return;
        }

        for($i = 0; $i < count($date[$parent_id]); $i++) {

            $tmp['id']   = $date[$parent_id][$i]['id'];
            $tmp['slug'] = $date[$parent_id][$i]['slug'];
            $tmp['name'] = $hyphen.$date[$parent_id][$i]['name'];
            $tmp['description'] = $date[$parent_id][$i]['description'];
            $tmp['keywords'] = $date[$parent_id][$i]['keywords'];
            $tmp['position'] = $date[$parent_id][$i]['position'];
            $tmp['is_visible'] = $date[$parent_id][$i]['is_visible'];
            $tmp['level']= $level;

            $res[]       = $tmp;

            $hyphen .= '-';
            $level++;
            $this->createTreeHyphen($date, $date[$parent_id][$i]['id'], $hyphen, $res, $level);
            $level--;
            $hyphen = substr($hyphen, 1);

        }

        return $res;

    }

    public function createTreeHtml($date, $parent_id = 0, &$res = '')
    {
        if(empty($date[$parent_id])){
            return;
        }

        $res .= '<ul>';

        for($i = 0; $i < count($date[$parent_id]); $i++) {

            $res .= '<li>'.$date[$parent_id][$i]['name'];

            $res .= '<a href="'.route("edit_categories_a", $date[$parent_id][$i]['id']).'"> Edit </a>';
            $res .= '<a href="'.route("delete_cat_a", $date[$parent_id][$i]['id']).'">Delete </a>';

            $res .= '</li>';

            $this->createTreeHtml($date, $date[$parent_id][$i]['id'], $res);

        }
        $res .= '</ul>';

        return $res;
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\CategoryProduct;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Collection;

class CategoryController extends FrontendController
{
    public function index(Product $product)
    {
        $paginate = $product->filter()->paginate(10);
        $categories = Category::with('productsCount')->get();

        return $this->_view('categories.index', compact('categories', 'paginate'));
    }

    public function show(Category $category)
    {
        $paginate = $category->products()->filter()->paginate(10);
        $categories = Category::with('productsCount')->get();

        return $this->_view('categories.show', compact('categories', 'category', 'paginate'));
    }
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Facades\SubDomainService;
use App\Http\Requests\Dashboard\StoreCategory;
use App\Http\Requests\Dashboard\UpdateCategory;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Validator;

class CategoryController extends Controller
{
    public function index(Category $category)
    {
        $categories = $category->all();

        $prepareTree = $category->preparationForTree($categories->toArray());

        $tree = null;
        $categoryModel = null;

        if (!empty($prepareTree)){
            $tree = $category->createTreeHyphen($prepareTree,  min(array_keys($prepareTree)));
            $categoryModel = $category;
        }

        return view('dashboard.categories.index', compact('categoryModel', 'tree'));
    }

    public function create(Category $category)
    {
        $categories = Category::all();

        $tree = null;
        $prepareTree = null;

        if(!$categories->isEmpty()){
            $prepareTree = $category->preparationForTree($categories->toArray());
            $tree = $category->createTreeHyphen($prepareTree,  min(array_keys($prepareTree)));
        }

        return view('dashboard.categories.create', compact('tree'));
    }

    public function store(StoreCategory $request, Category $category)
    {
        $category->fill($request->validated());

        $category->slug = str_slug($category->name);

        if (is_null($category->parent_id)){
            $category->parent_id = 0;
            $category->position  = 1 + ($category->max('position') ?? 0);
        }else{
            $category->position  = 1 + ($category->whereParentId($category->parent_id)->max('position') ?? 0);
        }

        $category->save();

        return redirect()->route('dashboard.store.categories.index');
    }

    public function edit(Category $category)
    {
        $categories = $category->where('id', '!=', $category->id)->where('parent_id', '!=', $category->id)->get();

        $tree = null;
        $prepareTree = null;

        if(!$categories->isEmpty()){
            $prepareTree = $category->preparationForTree($categories->toArray());
            $tree = $category->createTreeHyphen($prepareTree, min(array_keys($prepareTree)));
        }

        return view('dashboard.categories.edit', compact('category', 'tree'));
    }

    public function update(UpdateCategory $request, Category $category)
    {
        $valid = Validator::make($request->all(), [
            'parent_id'     => 'required',
        ]);

        $id = Category::where('slug', $request->segment(4))->first()->id;

        $valid->sometimes(
            ['parent_id'],
            Rule::exists('categories', 'id')->where(function ($query) use ($id) {
                return $query->where('store_id', SubDomainService::getStoreId())->where('parent_id', '!=', $id);
            }),
            function($input){
                return ($input->parent_id != 0) ? true : false;
            }
        );

        if($valid->fails()){
            return redirect()->back()
                ->withErrors($valid)
                ->withInput();
        }

        $category->fill($request->validated());
        $category->slug = str_slug($category->name);
        $category->parent_id = $request->parent_id;

        $category->save();

        return redirect()->route('dashboard.store.categories.index');
    }

    public function destroy(Category $category)
    {
        DB::transaction(function () use ($category){
            $category->where('parent_id', $category->id)->update(['parent_id' => $category->parent_id]);
            $category->delete();
        });

        return redirect()->route('dashboard.store.categories.index');
    }
}

resources/views/designs/default/categories/index.blade.php
@extends('designs.'.SubDomain::getDesign().'.layouts.default')

@section('tags')



@endsection

@section('content')
    <div id="search-results" class="section-container bg-silver">
        <!-- BEGIN container -->
        <div class="container">
            <!-- BEGIN search-container -->
            <div class="search-container">
                <!-- BEGIN search-content -->
                <div class="search-content">
                    <!-- BEGIN search-toolbar -->
                    <div class="search-toolbar">
                        <!-- BEGIN row -->
                        <div class="row">
                            <div class="col-md-6">
                                <h4>Все категория</h4>
                            </div>
                            <div class="col-md-6 text-right">
                                <ul class="sort-list">
                                    <li class="text"><i class="fa fa-filter"></i> Сортировать:</li>
                                    {{--<li class="active"><a href="#">Popular</a></li>--}}
                                    <li>
                                        <a href="{{request()->fullUrlWithQuery(['sale' => request()->has('sale')?!request('sale'):1, 'price_by' => null])}}">По скидке</a>
                                        @if(request()->has('sale'))
                                            <span>{!! request('sale')?'&uarr;':'&darr;' !!}</span>
                                        @endif
                                    </li>
                                    <li>
                                        <a href="{{request()->fullUrlWithQuery(['price_by' => request()->has('price_by')?!request('price_by'):1, 'sale' => null])}}">По цене</a>
                                        @if(request()->has('price_by'))
                                            <span>{!! request('price_by')?'&uarr;':'&darr;' !!}</span>
                                        @endif
                                    </li>
                                </ul>
                            </div>
                            <!-- END col-6 -->
                        </div>
                        <!-- END row -->
                    </div>
                    <!-- END search-toolbar -->
                    <!-- BEGIN search-item-container -->
                    <div class="search-item-container">
                        @foreach(with(new Illuminate\Support\Collection($paginate->items()))->chunk(3) as $chunk)
                            <div class="item-row">
                                @foreach($chunk as $product)
                                    <div class="item item-thumbnail">
                                        <a href="{{route('frontend.products.show', $product->slug)}}" class="item-image">
                                            <img src="{{asset($product->picture)}}" alt="" />
                                        </a>
                                        <div class="item-info">
                                            <h4 class="item-title">
                                                <a href="{{route('frontend.products.show', $product->slug)}}">{{$product->name}}</a>
                                            </h4>
                                            <p class="item-desc">{{$product->short_description}}</p>
                                            @if($product->price != $product->sale_price)
                                                <div class="item-discount-price">
                                                    <span>{{$product->price}} <small>грн.</small></span>
                                                </div>
                                            @endif
                                            <div class="item-price">
                                                <span>{{($product->sale_price != $product->price)?$product->sale_price:$product->price}}<small>грн.</small></span>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        @endforeach
                    </div>
                    <!-- END search-item-container -->
                    <!-- BEGIN pagination -->
                    <div class="text-center">
                        {{ $paginate->appends(request()->except('page'))->links() }}
                    </div>
                    <!-- END pagination -->
                </div>
                <!-- END search-content -->
                <!-- BEGIN search-sidebar -->
                <div class="search-sidebar">
                    <h4 class="title">Фильтровать по</h4>
                    <form action="{{route('frontend.categories.index')}}" method="get" name="filter_form">
                        <div class="form-group">
                            <label class="control-label">Поиск</label>
                            <a class="pull-right" href="{{route('frontend.categories.index')}}">Сбросить</a>
                            <input type="text" class="form-control input-sm" name="s" value="{{request('s')}}" placeholder="Enter Keywords" />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Цена</label>
                            <div class="row row-space-0">
                                <div class="col-md-5">
                                    <input type="number" class="form-control input-sm" name="price_from" value="{{request('price_from')??1}}" placeholder="От" />
                                </div>
                                <div class="col-md-2 text-center p-t-5 f-s-12 text-muted">до</div>
                                <div class="col-md-5">
                                    <input type="number" class="form-control input-sm" name="price_to" value="{{request('price_to')??50000}}" placeholder="До" />
                                </div>
                            </div>
                        </div>
                        <div class="m-b-30">
                            <button type="submit" class="btn btn-sm btn-inverse"><i class="fa fa-search"></i> Поиск</button>
                        </div>
                    </form>
                    <h4 class="title m-b-0">Категории</h4>
                    <ul class="search-category-list">
                        <li>
                            <a href="{{route('frontend.categories.index')}}">
                                Все категории
                                <span class="pull-right">></span>
                            </a>
                        </li>
                        @foreach($categories as $cat)
                            @if(!is_null($cat->productsCount))
                                <li><a href="{{route('frontend.categories.show', $cat->slug)}}">{{$cat->name}}<span class="pull-right">{{$cat->productsCount->count}}</span></a></li>
                            @endIf
                        @endForeach
                    </ul>
                </div>
                <!-- END search-sidebar -->
            </div>
            <!-- END search-container -->
        </div>
        <!-- END container -->
    </div>
    <!-- END search-results -->

@endsection

resources/views/designs/default/categories/show.blade.php
@extends('designs.'.SubDomain::getDesign().'.layouts.default')

@section('tags')

    <title>{{$category->name}}</title>

    <meta name="description" content="{{$category->short_description}}" />

    <meta property="og:title" content="{{$category->name}}" />
    <meta property="og:description" content="{{$category->description}}" />
    <meta property="og:locale" content="ru_RU" />
    <meta property="og:type" content="shop" />
    <meta property="og:url" content="{{route('frontend.categories.show', $category->slug)}}" />

    <meta name="twitter:title" content="{{$category->name}}" />
    <meta name="twitter:description" content="{{$category->description}}">
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@<?= OptionsFacade::getMetaMainSite()?>" />


@endsection

@section('content')
    <div id="search-results" class="section-container bg-silver">
        <div class="container">
            <div class="search-container">
                <div class="search-content">
                    <div class="search-toolbar">
                        <div class="row">
                            <div class="col-md-6">
                                <h4>Категория "{{($category->productsCount) ? $category->productsCount->count : '0'}})</h4>
                            </div>
                            <div class="col-md-6 text-right">
                                <ul class="sort-list">
                                    <li class="text"><i class="fa fa-filter"></i> Сортировать:</li>
                                    {{--<li class="active"><a href="#">Popular</a></li>--}}
                                    <li>
                                        <a href="{{request()->fullUrlWithQuery(['sale' => request()->has('sale')?!request('sale'):1, 'price_by' => null])}}">По скидке</a>
                                        @if(request()->has('sale'))
                                            <span>{!! request('sale')?'&uarr;':'&darr;' !!}</span>
                                        @endif
                                    </li>
                                    <li>
                                        <a href="{{request()->fullUrlWithQuery(['price_by' => request()->has('price_by')?!request('price_by'):1, 'sale' => null])}}">По цене</a>
                                        @if(request()->has('price_by'))
                                            <span>{!! request('price_by')?'&uarr;':'&darr;' !!}</span>
                                        @endif
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="search-item-container">
                        @foreach(with(new Illuminate\Support\Collection($paginate->items()))->chunk(3) as $chunk)
                            <div class="item-row">
                                @foreach($chunk as $product)
                                    <div class="item item-thumbnail">
                                        <a href="{{route('frontend.products.show', $product->slug)}}" class="item-image">
                                            <img src="{{asset($product->picture)}}" alt="" />
                                        </a>
                                        <div class="item-info">
                                            <h4 class="item-title">
                                                <a href="{{route('frontend.products.show', $product->slug)}}">{{$product->name}}</a>
                                            </h4>
                                            <p class="item-desc">{{$product->short_description}}</p>
                                            @if($product->price != $product->sale_price)
                                                <div class="item-discount-price">
                                                    <span>{{$product->price}} <small>{{$product->currency}}</small></span>
                                                </div>
                                            @endif
                                            <div class="item-price">
                                                <span>{{($product->sale_price != $product->price)?$product->sale_price:$product->price}}<small> {{$product->currency}}</small></span>
                                            </div>
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        @endforeach
                    </div>
                    <div class="text-center">
                        {{ $paginate->appends(request()->except('page'))->links() }}
                    </div>
                </div>
                <div class="search-sidebar">
                    <h4 class="title">Фильтровать по</h4>
                    <form action="{{route('frontend.categories.show', $category->slug)}}" method="get" name="filter_form">
                        <div class="form-group">
                            <label class="control-label">Поиск</label>
                            <a class="pull-right" href="{{route('frontend.categories.show', $category->slug)}}">Сбросить</a>
                            <input type="text" class="form-control input-sm" name="s" value="{{request('s')}}" placeholder="Enter Keywords" />
                        </div>
                        <div class="form-group">
                            <label class="control-label">Цена</label>
                            <div class="row row-space-0">
                                <div class="col-md-5">
                                    <input type="number" class="form-control input-sm" name="price_from" value="{{request('price_from')??1}}" placeholder="От" />
                                </div>
                                <div class="col-md-2 text-center p-t-5 f-s-12 text-muted">до</div>
                                <div class="col-md-5">
                                    <input type="number" class="form-control input-sm" name="price_to" value="{{request('price_to')??50000}}" placeholder="До" />
                                </div>
                            </div>
                        </div>
                        <div class="m-b-30">
                            <button type="submit" class="btn btn-sm btn-inverse"><i class="fa fa-search"></i> Поиск</button>
                        </div>
                    </form>
                    <h4 class="title m-b-0">Категории</h4>
                    <ul class="search-category-list">
                        <li>
                            <a href="{{route('frontend.categories.index')}}">
                                Все категории
                                <span class="pull-right">></span>
                            </a>
                        </li>
                        @foreach($categories as $cat)
                            @if(!is_null($cat->productsCount))
                                <li><a href="{{route('frontend.categories.show', $cat->slug)}}">{{$cat->name}}<span class="pull-right">{{$cat->productsCount->count}}</span></a></li>
                            @endIf
                        @endForeach
                    </ul>
                </div>
            </div>
        </div>
    </div>

@endsection